-- WealthBridge Tax Stack — Supabase RLS Policies
-- Apply after creating tables in Supabase via the dashboard or CLI.
-- Generated by supabase/rls_helpers.py

-- tax_records
ALTER TABLE tax_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY tax_records_owner_only
  ON tax_records
  FOR ALL
  TO authenticated
  USING ((created_by::text = auth.uid()::text))
  WITH CHECK ((created_by::text = auth.uid()::text));
CREATE POLICY tax_records_admin_bypass
  ON tax_records
  FOR ALL
  TO service_role
  USING (true);

-- rd_projects
ALTER TABLE rd_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY rd_projects_owner_only
  ON rd_projects
  FOR ALL
  TO authenticated
  USING ((record_id IN (SELECT id FROM tax_records WHERE created_by::text = auth.uid()::text)))
  WITH CHECK ((record_id IN (SELECT id FROM tax_records WHERE created_by::text = auth.uid()::text)));
CREATE POLICY rd_projects_admin_bypass
  ON rd_projects
  FOR ALL
  TO service_role
  USING (true);

-- tax_documents
ALTER TABLE tax_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY tax_documents_owner_only
  ON tax_documents
  FOR ALL
  TO authenticated
  USING ((created_by::text = auth.uid()::text))
  WITH CHECK ((created_by::text = auth.uid()::text));
CREATE POLICY tax_documents_admin_bypass
  ON tax_documents
  FOR ALL
  TO service_role
  USING (true);
